#makefile для simple_inline_asm_in_C.c
simple_inline_asm_in_C: simple_inline_asm_in_C.c
# параметр -masm=intel обязателен при использовании встроенного ассемблерного кода
	gcc -g -o  simple_inline_asm_in_C simple_inline_asm_in_C.c -masm=intel -no-pie  # параметр -masm=intel обязателен при использовании встроенного ассемблерного кода

