#makefile для extended_inline_asm_in_C.c
extended_inline_asm_in_C: extended_inline_asm_in_C.c
# параметр -masm=intel обязателен при использовании встроенного ассемблерного кода
	gcc -g -o  extended_inline_asm_in_C extended_inline_asm_in_C.c -masm=intel -no-pie  # параметр -masm=intel обязателен при использовании встроенного ассемблерного кода

